Update pyproject.toml for lora dependencies;
Currently the LoRA requires >= 0.27.2 to LoRA otherwise it would turn out to be a TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'