Update llava_llama.py for transformers 4.39.1
To resolve error `TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'` introduced by 

https://github.com/huggingface/transformers/pull/29467